### ISSUE TITLE
PHP Notice:  Undefined variable: http_response_header in common.inc.php on line 125

### ISSUE THREAD

**Issue by weeb0** [cdhowie/Bitcoin-mining-proxy#40] opened 2011-07-28 14:44 UTC
using latest git version,

I'm getting the message in error_log of apache.

I posted a new topic in bitcoin forum : ( http://forum.bitcoin.org/index.php?topic=32547.msg406460#msg406460 )

**Comment by weeb0** [comment] 2011-07-28 17:54
I explored this, and it appear when using the http_response_header in a function, it is necessary to pass the variable as a function parameter.

I changed the function header to :
function place_json_call($object, $url, $username = '', $password = '', &$headers, $timeout = 2,$http_response_header)

and the line calling the function should be like : 
    $response = place_json_call($request, $row['url'], $row['username'], $row['password'], $headers, http_response_header);

**Comment by alinnow** [comment] 2011-07-28 18:01
Duplicate of #14

Find your php.ini and uncomment `allow_url_fopen = On` or change it to On if it's Off

**Comment by weeb0** [comment] 2011-07-28 18:05
I don't agree.  The allow_url_fopen is already On (this is validated with phpinfo() ) and doing the changes suggested in my second comment solve the issue.

**Comment by alinnow** [comment] 2011-07-28 18:27
`$http_response_header` is a reserved variable when `allow_url_fopen = On`: you should not create it.

The [PHP docs](http://www.php.net/manual/en/reserved.variables.httpresponseheader.php) indicate that the syntax is correct and the variable should be defined without explicit declaration

It's likely that the `@file_get_contents` call failed (line 123), remove the @ and see what errors come up then. You may also need to comment out the `error_reporting(E_ERROR | E_USER_ERROR);` line in config.inc.php

**Closed as completed** 2011-07-28 18:42 UTC
